[tool.poetry]
name = "repl_python3_covid-desktop-notifier"
version = "0.1.0"
description = ""
authors = ["dev9033 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
plyer = "^2.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
